world_frame: world
takeoff_delay: 6.0
heartbeat_timeout: 1.0
height_tolerance: 0.4
minimum_vertical_separation: 4.0
minimum_3d_separation: 3.0
trajectory_prediction_horizon: 4.0
trajectory_prediction_period: 0.25
takeoff_protection_radius: 3.0
uav2_takeoff_height: 4.0
landing_protection_radius: 3.0
uav1_home_position: [0.0, 0.0, 0.0]
uav2_home_position: [2.0, 0.0, 0.0]
uav2_final_height: 24.0
