#!/usr/bin/env python3
"""Offline qualification for the frozen Forest Randomization map pool.

The QA path is deliberately independent from EGO and the task planner. It
reproduces the C++ generator's standard MT19937 stream, validates checked-in
worlds, measures real cylinder overlap, and runs a conservative 2-D grid
reachability check only as map qualification evidence.
"""

from __future__ import annotations

import argparse
from collections import deque
import hashlib
import json
import math
from pathlib import Path
import xml.etree.ElementTree as ET


TOL = 1.0e-5
# Gazebo's saved-world formatter uses six significant decimal digits, so a
# coordinate near 50 m can be rounded by slightly more than 5e-5 m.
WORLD_SERIALIZATION_TOL = 6.0e-5


class StandardMt19937:
    """Small exact implementation of the C++ ``std::mt19937`` engine."""

    _N = 624
    _M = 397
    _MATRIX_A = 0x9908B0DF
    _UPPER_MASK = 0x80000000
    _LOWER_MASK = 0x7FFFFFFF

    def __init__(self, seed: int):
        value = int(seed)
        if value < 0 or value > 0xFFFFFFFF:
            raise ValueError("raw seed must fit uint32")
        self._state = [0] * self._N
        self._state[0] = value
        for index in range(1, self._N):
            previous = self._state[index - 1]
            self._state[index] = (
                1812433253 * (previous ^ (previous >> 30)) + index
            ) & 0xFFFFFFFF
        self._index = self._N

    def _twist(self):
        for index in range(self._N):
            value = (self._state[index] & self._UPPER_MASK) | (
                self._state[(index + 1) % self._N] & self._LOWER_MASK
            )
            shifted = value >> 1
            if value & 1:
                shifted ^= self._MATRIX_A
            self._state[index] = self._state[(index + self._M) % self._N] ^ shifted
        self._index = 0

    def next_uint32(self) -> int:
        if self._index >= self._N:
            self._twist()
        value = self._state[self._index]
        self._index += 1
        value ^= value >> 11
        value ^= (value << 7) & 0x9D2C5680
        value ^= (value << 15) & 0xEFC60000
        value ^= value >> 18
        return value & 0xFFFFFFFF

    def uniform(self, minimum: float, maximum: float) -> float:
        unit = self.next_uint32() / 4294967296.0
        return minimum + unit * (maximum - minimum)


def load_config(path: Path) -> dict:
    value = json.loads(path.read_text(encoding="utf-8"))
    required = {
        "schema_version", "map", "cylinders", "zones", "qualification",
        "seed_pool", "scheduler",
    }
    if set(value) != required:
        raise ValueError("forest config top-level keys do not match the frozen contract")
    return value


def generated_layout(raw_seed: int, config: dict) -> list[dict]:
    engine = StandardMt19937(raw_seed)
    radius_min, radius_max = map(float, config["cylinders"]["radius_m"])
    y_min, y_max = map(float, config["map"]["center_sampling_y_m"])
    height = float(config["cylinders"]["height_m"])
    records = []
    object_index = 0
    for zone_name in ("sparse", "medium", "dense"):
        zone = config["zones"][zone_name]
        x_min, x_max = map(float, zone["x_m"])
        area = (x_max - x_min) * float(config["map"]["size_y_m"])
        count = int(math.floor(float(zone["density_per_m2"]) * area))
        for _ in range(count):
            radius = engine.uniform(radius_min, radius_max)
            # The checked-in worlds were generated by GCC 9 from the original
            # Eigen constructor expression, whose two RNG arguments were
            # evaluated Y then X. The C++ source now makes this order explicit.
            y = engine.uniform(y_min, y_max)
            x = engine.uniform(x_min + radius, x_max - radius)
            records.append(
                {
                    "name": "{}_{}".format(zone_name, object_index),
                    "zone": zone_name,
                    "x": x,
                    "y": y,
                    "z": height / 2.0,
                    "radius": radius,
                    "height": height,
                }
            )
            object_index += 1
    return records


def _close(actual: float, expected: float) -> bool:
    return math.isclose(actual, expected, rel_tol=0.0, abs_tol=TOL)


def _pose(model: ET.Element) -> tuple[float, float, float]:
    values = [float(value) for value in model.findtext("pose", "").split()]
    if len(values) < 3:
        raise ValueError("model {} has no valid pose".format(model.get("name")))
    return values[0], values[1], values[2]


def parse_world(world_path: Path, config: dict) -> list[dict]:
    root = ET.parse(world_path).getroot()
    world = root.find("world")
    if world is None:
        raise ValueError("{} has no world".format(world_path))
    ground = world.find("./model[@name='forest_ground_60x20']")
    if ground is None:
        raise ValueError("{} has no frozen forest ground".format(world_path))
    gx, gy, gz = _pose(ground)
    expected_size = "{} {}".format(
        int(config["map"]["size_x_m"]), int(config["map"]["size_y_m"])
    )
    collision_size = ground.findtext("./link/collision/geometry/plane/size", "")
    visual_size = ground.findtext("./link/visual/geometry/plane/size", "")
    if not (_close(gx, 30.0) and _close(gy, 0.0) and _close(gz, 0.0)):
        raise ValueError("{} ground center is not (30,0,0)".format(world_path))
    if collision_size.strip() != expected_size or visual_size.strip() != expected_size:
        raise ValueError("{} ground is not {} m".format(world_path, expected_size))

    records = []
    for model in world.findall("model"):
        cylinder = model.find("./link/collision/geometry/cylinder")
        if cylinder is None:
            continue
        visual = model.find("./link/visual/geometry/cylinder")
        if visual is None:
            raise ValueError("{} model {} has no cylinder visual".format(world_path, model.get("name")))
        name = str(model.get("name", ""))
        zone = next(
            (candidate for candidate in ("sparse", "medium", "dense") if name.startswith(candidate + "_")),
            None,
        )
        if zone is None:
            raise ValueError("{} has unexpected cylinder {}".format(world_path, name))
        x, y, z = _pose(model)
        radius = float(cylinder.findtext("radius", "nan"))
        height = float(cylinder.findtext("length", "nan"))
        if not _close(radius, float(visual.findtext("radius", "nan"))):
            raise ValueError("{} {} collision/visual radius mismatch".format(world_path, name))
        if not _close(height, float(visual.findtext("length", "nan"))):
            raise ValueError("{} {} collision/visual height mismatch".format(world_path, name))
        records.append(
            {"name": name, "zone": zone, "x": x, "y": y, "z": z, "radius": radius, "height": height}
        )
    return sorted(records, key=lambda item: int(item["name"].split("_")[-1]))


def layout_hash(records: list[dict]) -> str:
    lines = [
        "{name}|{zone}|{x:.9f}|{y:.9f}|{z:.9f}|{radius:.9f}|{height:.9f}".format(**item)
        for item in records
    ]
    return hashlib.sha256("\n".join(lines).encode("utf-8")).hexdigest()


def overlap_audit(records: list[dict]) -> dict:
    pairs = []
    for index, left in enumerate(records):
        for right in records[index + 1 :]:
            clearance = math.hypot(left["x"] - right["x"], left["y"] - right["y"])
            clearance -= left["radius"] + right["radius"]
            pairs.append(
                {"left": left["name"], "right": right["name"], "surface_clearance_m": clearance}
            )
    pairs.sort(key=lambda item: item["surface_clearance_m"])
    overlaps = [item for item in pairs if item["surface_clearance_m"] < -TOL]
    return {
        "minimum_surface_clearance_m": pairs[0]["surface_clearance_m"] if pairs else None,
        "overlap_count": len(overlaps),
        "overlap_pairs": overlaps,
    }


def traversability_audit(records: list[dict], config: dict) -> dict:
    qa = config["qualification"]
    resolution = float(qa["grid_resolution_m"])
    clearance = float(qa["qa_clearance_m"])
    size_x = float(config["map"]["size_x_m"])
    size_y = float(config["map"]["size_y_m"])
    y_low = -size_y / 2.0 + clearance
    y_high = size_y / 2.0 - clearance
    x_low = clearance
    x_high = size_x - clearance
    nx = int(math.floor((x_high - x_low) / resolution)) + 1
    ny = int(math.floor((y_high - y_low) / resolution)) + 1

    def point(index_x: int, index_y: int) -> tuple[float, float]:
        return x_low + index_x * resolution, y_low + index_y * resolution

    blocked = bytearray(nx * ny)
    for iy in range(ny):
        for ix in range(nx):
            x, y = point(ix, iy)
            if any(
                math.hypot(x - item["x"], y - item["y"])
                < item["radius"] + clearance - TOL
                for item in records
            ):
                blocked[iy * nx + ix] = 1

    start_x_max = float(config["map"]["start_safe_x_m"][1])
    goal_x_min = float(config["map"]["end_safe_x_m"][0])
    queue = deque()
    visited = bytearray(nx * ny)
    for iy in range(ny):
        for ix in range(nx):
            x, _ = point(ix, iy)
            flat = iy * nx + ix
            if x <= start_x_max + TOL and not blocked[flat]:
                visited[flat] = 1
                queue.append((ix, iy))
    reached = None
    directions = ((-1, -1), (-1, 0), (-1, 1), (0, -1), (0, 1), (1, -1), (1, 0), (1, 1))
    while queue:
        ix, iy = queue.popleft()
        x, y = point(ix, iy)
        if x >= goal_x_min - TOL:
            reached = (x, y)
            break
        for dx, dy in directions:
            tx, ty = ix + dx, iy + dy
            if tx < 0 or tx >= nx or ty < 0 or ty >= ny:
                continue
            flat = ty * nx + tx
            if blocked[flat] or visited[flat]:
                continue
            if dx and dy and (blocked[iy * nx + tx] or blocked[ty * nx + ix]):
                continue
            visited[flat] = 1
            queue.append((tx, ty))
    return {
        "passed": reached is not None,
        "failure_reason": "" if reached is not None else "no inflated Start-Safe to End-Safe path",
        "qa_clearance_m": clearance,
        "grid_resolution_m": resolution,
        "reachable_cell_count": int(sum(visited)),
        "goal_reached_xy": None if reached is None else list(reached),
    }


def qualify_records(records: list[dict], config: dict, expected_raw_seed: int | None = None) -> dict:
    failures = []
    expected_counts = {}
    counts = {zone: 0 for zone in ("sparse", "medium", "dense")}
    radius_min, radius_max = map(float, config["cylinders"]["radius_m"])
    map_y_low = -float(config["map"]["size_y_m"]) / 2.0
    map_y_high = -map_y_low
    height = float(config["cylinders"]["height_m"])
    for zone_name in counts:
        zone = config["zones"][zone_name]
        x_min, x_max = map(float, zone["x_m"])
        area = (x_max - x_min) * float(config["map"]["size_y_m"])
        expected_counts[zone_name] = int(math.floor(float(zone["density_per_m2"]) * area))
    if len(records) != sum(expected_counts.values()):
        failures.append("total_count")
    for item in records:
        counts[item["zone"]] += 1
        x_min, x_max = map(float, config["zones"][item["zone"]]["x_m"])
        if item["x"] - item["radius"] < x_min - TOL or item["x"] + item["radius"] > x_max + TOL:
            failures.append("zone_boundary:" + item["name"])
        if item["y"] - item["radius"] < map_y_low - TOL or item["y"] + item["radius"] > map_y_high + TOL:
            failures.append("map_y_boundary:" + item["name"])
        if not radius_min - TOL <= item["radius"] <= radius_max + TOL:
            failures.append("radius:" + item["name"])
        if not _close(item["height"], height) or not _close(item["z"], height / 2.0):
            failures.append("height_or_z:" + item["name"])
        if not _close(item["z"] - item["height"] / 2.0, 0.0) or not _close(
            item["z"] + item["height"] / 2.0, height
        ):
            failures.append("vertical_extent:" + item["name"])
    if counts != expected_counts:
        failures.append("density_count")
    overlap = overlap_audit(records)
    # Stricter pool admission only; no rejection sampling or spacing is added.
    if overlap["overlap_count"]:
        failures.append("geometric_overlap")
    traversability = traversability_audit(records, config)
    if not traversability["passed"]:
        failures.append("traversability")
    if expected_raw_seed is not None:
        expected = generated_layout(expected_raw_seed, config)
        if len(records) != len(expected):
            failures.append("world_does_not_match_raw_seed")
        else:
            for actual, generated in zip(records, expected):
                if actual["name"] != generated["name"] or any(
                    not math.isclose(
                        actual[name], generated[name], rel_tol=0.0,
                        abs_tol=WORLD_SERIALIZATION_TOL,
                    )
                    for name in ("x", "y", "z", "radius", "height")
                ):
                    failures.append("world_does_not_match_raw_seed")
                    break
    return {
        "passed": not failures,
        "failures": sorted(set(failures)),
        "counts": {**counts, "total": sum(counts.values())},
        "expected_counts": {**expected_counts, "total": sum(expected_counts.values())},
        "layout_sha256": layout_hash(records),
        "overlap": overlap,
        "traversability": traversability,
    }


def select_raw_seeds(config: dict, maximum_raw_seed: int) -> list[dict]:
    selected = []
    for raw_seed in range(maximum_raw_seed + 1):
        records = generated_layout(raw_seed, config)
        result = qualify_records(records, config)
        if result["passed"]:
            selected.append(
                {
                    "raw_seed": raw_seed,
                    "minimum_surface_clearance_m": result["overlap"]["minimum_surface_clearance_m"],
                    "layout_sha256": result["layout_sha256"],
                }
            )
        if len(selected) == 10:
            break
    if len(selected) != 10:
        raise ValueError("fewer than ten qualifying raw seeds were found")
    return selected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--world-dir", type=Path)
    parser.add_argument("--report-json", type=Path)
    parser.add_argument("--select-raw-seeds", action="store_true")
    parser.add_argument("--maximum-raw-seed", type=int, default=10000)
    args = parser.parse_args()
    config = load_config(args.config)
    if args.select_raw_seeds:
        print(json.dumps(select_raw_seeds(config, args.maximum_raw_seed), indent=2, sort_keys=True))
        return 0
    if args.world_dir is None:
        parser.error("--world-dir is required unless --select-raw-seeds is used")

    results = []
    hashes = set()
    for value in config["seed_pool"]:
        logical_seed = int(value["logical_seed"])
        raw_seed = int(value["raw_seed"])
        path = args.world_dir / "learning_speed_forest_v1_seed{}.world".format(logical_seed)
        records = parse_world(path, config)
        result = qualify_records(records, config, expected_raw_seed=raw_seed)
        deterministic = generated_layout(raw_seed, config) == generated_layout(raw_seed, config)
        if not deterministic:
            result["failures"].append("non_deterministic_generation")
            result["passed"] = False
        if result["layout_sha256"] in hashes:
            result["failures"].append("duplicate_layout")
            result["passed"] = False
        hashes.add(result["layout_sha256"])
        result.update(
            {
                "logical_seed": logical_seed,
                "raw_seed": raw_seed,
                "role": value["role"],
                "world": str(path),
                "deterministic": deterministic,
            }
        )
        results.append(result)
        print(
            "logical_seed={logical} raw_seed={raw} role={role} counts={counts} "
            "min_surface_clearance_m={clearance:.6f} overlaps={overlaps} "
            "traversability={traversability} deterministic={deterministic} verdict={verdict}".format(
                logical=logical_seed,
                raw=raw_seed,
                role=value["role"],
                counts=result["counts"],
                clearance=result["overlap"]["minimum_surface_clearance_m"],
                overlaps=result["overlap"]["overlap_count"],
                traversability="PASS" if result["traversability"]["passed"] else "FAIL",
                deterministic=deterministic,
                verdict="PASS" if result["passed"] else "FAIL:" + ",".join(result["failures"]),
            )
        )
    payload = {
        "schema_version": "astradrone_forest_qualification_v2.0",
        "config": str(args.config),
        "all_passed": all(item["passed"] for item in results),
        "results": results,
    }
    if args.report_json:
        args.report_json.parent.mkdir(parents=True, exist_ok=True)
        args.report_json.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    if not payload["all_passed"]:
        return 2
    print("PASS: all logical seed0-9 maps satisfy deterministic geometry, zero-overlap and traversability QA")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
